### ISSUE TITLE
BUG-010 Reporters of bugs/features don't get notified on resolvement

### ISSUE THREAD

**Issue by lorddusk** [5ecrawler/tracker#3]
**What is the bug?**: Reporters of bugs/features don't get notified on resolvement
**Severity**: Medium
**Steps to reproduce**: When reporting a bug/feature the reporter doesn't get added to the notifcation group.

- LordDusk#0001
Verification: 0

**Comment by 5ecrawlreporter** [comment]
Note - LordDusk#0001

Resolved - Patched in build BUG-023 (CrawlerEmporium/5eCrawler#32)
